[tool.poetry]
name = "projetmlops"
version = "0.1.0"
description = "Prediction prix immo californie"
authors = ["Aya Elhaouitti"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
