name: CI/CD Pipeline for California Housing Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "requirements.txt"
          poetry install

      - name: Run Pytest
        run: poetry run pytest -v

  api_deploy:
    name: Build and Test API
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Start API with nohup
        run: |
          nohup poetry run python main_californiaHousing.py &
          sleep 10  # Donne le temps à l'API de démarrer

      - name: Test API
        run: poetry run pytest tests/test_api.py -v

      - name: Stop background process
        if: always()
        run: kill $(ps aux | grep 'main_californiaHousing.py' | grep -v grep | awk '{print $2}')

  dockerize:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
