name: CI/CD Pipeline for California Housing Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Port Availability
        run: |
          if lsof -i:8000; then
            echo "Port 8000 is already in use"
            exit 1
          else
            echo "Port 8000 is available"
          fi      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start API with Uvicorn
        run: |
          uvicorn main_tests:app --host 0.0.0.0 --port 8000 &
          sleep 20  # Increased the sleep time to ensure the API is up

      - name: Check API health
        run: |
          curl --fail http://127.0.0.1:8000/health || exit 1

      - name: Test API
        run: |
          poetry run pytest tests/test_api.py -v

      - name: Stop background process
        if: always()
        run: kill $(ps aux | grep 'uvicorn' | grep -v grep | awk '{print $2}')
