name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI server
      run: |
        nohup python main_californiaHousing.py &
        sleep 5  # Attendre quelques secondes que le serveur démarre

    - name: Run tests
      run: pytest -v

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Build l’image Docker
      - name: Build Docker Image
        run: docker build -t housing-prediction-api .

  deploy:
    name: Deploy Application (Placeholder)
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Déployer (remplacer avec une commande ou script réel)
      - name: Deploy Application
        run: |
          echo "Déploiement en cours..."
          # Ajouter ici les étapes pour déployer sur un serveur ou une plateforme cloud
